apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-service
  namespace: tic-tac-toe-namespace
spec:
  selector:
    app: tic-tac-toe
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30110
  type: NodePort